// Code generated by protoc-gen-go.
// source: gcan.proto
// DO NOT EDIT!

/*
Package gcanpb is a generated protocol buffer package.

It is generated from these files:
	gcan.proto

It has these top-level messages:
	MessageSet
	Message
	SendRequest
	SendResponse
	ReceiveRequest
*/
package gcanpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Err int32

const (
	Err_Unknown           Err = 0
	Err_CRCChecksumFailed Err = 1
)

var Err_name = map[int32]string{
	0: "Unknown",
	1: "CRCChecksumFailed",
}
var Err_value = map[string]int32{
	"Unknown":           0,
	"CRCChecksumFailed": 1,
}

func (x Err) String() string {
	return proto.EnumName(Err_name, int32(x))
}
func (Err) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MessageCompression int32

const (
	Message_NONE   MessageCompression = 0
	Message_ZLIB   MessageCompression = 1
	Message_SNAPPY MessageCompression = 2
)

var MessageCompression_name = map[int32]string{
	0: "NONE",
	1: "ZLIB",
	2: "SNAPPY",
}
var MessageCompression_value = map[string]int32{
	"NONE":   0,
	"ZLIB":   1,
	"SNAPPY": 2,
}

func (x MessageCompression) String() string {
	return proto.EnumName(MessageCompression_name, int32(x))
}
func (MessageCompression) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// MessageSet is the shared encoding that is used both on disk and over the wire.
type MessageSet struct {
	// Offset is not populated by producers.
	Offset   int64      `protobuf:"varint,1,opt,name=Offset" json:"Offset,omitempty"`
	Messages []*Message `protobuf:"bytes,2,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *MessageSet) Reset()                    { *m = MessageSet{} }
func (m *MessageSet) String() string            { return proto.CompactTextString(m) }
func (*MessageSet) ProtoMessage()               {}
func (*MessageSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageSet) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// Message is an individual key-value pair.
type Message struct {
	// CRC32 of all following fields
	CRC         uint32             `protobuf:"varint,1,opt,name=CRC" json:"CRC,omitempty"`
	Compression MessageCompression `protobuf:"varint,2,opt,name=Compression,enum=gcanpb.MessageCompression" json:"Compression,omitempty"`
	Key         []byte             `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Value       []byte             `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SendRequest struct {
	Topic      string      `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	MessageSet *MessageSet `protobuf:"bytes,2,opt,name=MessageSet" json:"MessageSet,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendRequest) GetMessageSet() *MessageSet {
	if m != nil {
		return m.MessageSet
	}
	return nil
}

type SendResponse struct {
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReceiveRequest struct {
	Topic     string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Partition int32  `protobuf:"varint,2,opt,name=Partition" json:"Partition,omitempty"`
	Offset    int64  `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
}

func (m *ReceiveRequest) Reset()                    { *m = ReceiveRequest{} }
func (m *ReceiveRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiveRequest) ProtoMessage()               {}
func (*ReceiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*MessageSet)(nil), "gcanpb.MessageSet")
	proto.RegisterType((*Message)(nil), "gcanpb.Message")
	proto.RegisterType((*SendRequest)(nil), "gcanpb.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "gcanpb.SendResponse")
	proto.RegisterType((*ReceiveRequest)(nil), "gcanpb.ReceiveRequest")
	proto.RegisterEnum("gcanpb.Err", Err_name, Err_value)
	proto.RegisterEnum("gcanpb.MessageCompression", MessageCompression_name, MessageCompression_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Producer service

type ProducerClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	SendStream(ctx context.Context, opts ...grpc.CallOption) (Producer_SendStreamClient, error)
}

type producerClient struct {
	cc *grpc.ClientConn
}

func NewProducerClient(cc *grpc.ClientConn) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := grpc.Invoke(ctx, "/gcanpb.Producer/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (Producer_SendStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Producer_serviceDesc.Streams[0], c.cc, "/gcanpb.Producer/SendStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerSendStreamClient{stream}
	return x, nil
}

type Producer_SendStreamClient interface {
	Send(*SendRequest) error
	Recv() (*SendResponse, error)
	grpc.ClientStream
}

type producerSendStreamClient struct {
	grpc.ClientStream
}

func (x *producerSendStreamClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerSendStreamClient) Recv() (*SendResponse, error) {
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Producer service

type ProducerServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	SendStream(Producer_SendStreamServer) error
}

func RegisterProducerServer(s *grpc.Server, srv ProducerServer) {
	s.RegisterService(&_Producer_serviceDesc, srv)
}

func _Producer_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ProducerServer).Send(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Producer_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServer).SendStream(&producerSendStreamServer{stream})
}

type Producer_SendStreamServer interface {
	Send(*SendResponse) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type producerSendStreamServer struct {
	grpc.ServerStream
}

func (x *producerSendStreamServer) Send(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerSendStreamServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Producer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcanpb.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Producer_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _Producer_SendStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

// Client API for Consumer service

type ConsumerClient interface {
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (Consumer_ReceiveClient, error)
}

type consumerClient struct {
	cc *grpc.ClientConn
}

func NewConsumerClient(cc *grpc.ClientConn) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (Consumer_ReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Consumer_serviceDesc.Streams[0], c.cc, "/gcanpb.Consumer/Receive", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consumer_ReceiveClient interface {
	Recv() (*MessageSet, error)
	grpc.ClientStream
}

type consumerReceiveClient struct {
	grpc.ClientStream
}

func (x *consumerReceiveClient) Recv() (*MessageSet, error) {
	m := new(MessageSet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Consumer service

type ConsumerServer interface {
	Receive(*ReceiveRequest, Consumer_ReceiveServer) error
}

func RegisterConsumerServer(s *grpc.Server, srv ConsumerServer) {
	s.RegisterService(&_Consumer_serviceDesc, srv)
}

func _Consumer_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServer).Receive(m, &consumerReceiveServer{stream})
}

type Consumer_ReceiveServer interface {
	Send(*MessageSet) error
	grpc.ServerStream
}

type consumerReceiveServer struct {
	grpc.ServerStream
}

func (x *consumerReceiveServer) Send(m *MessageSet) error {
	return x.ServerStream.SendMsg(m)
}

var _Consumer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcanpb.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _Consumer_Receive_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x4f, 0xaf, 0x93, 0x40,
	0x14, 0xc5, 0x3b, 0x8f, 0x3e, 0xca, 0xbb, 0xbc, 0x87, 0xbc, 0xf1, 0x4f, 0xc8, 0x73, 0x53, 0x59,
	0x18, 0x34, 0x91, 0x34, 0x74, 0xe5, 0xc2, 0x18, 0x8b, 0x35, 0x31, 0x6a, 0x4b, 0x8a, 0x9a, 0xe8,
	0x8e, 0xd2, 0xdb, 0x4a, 0x5a, 0x18, 0x9c, 0x01, 0x8d, 0x1b, 0xbf, 0x84, 0x5f, 0xd8, 0x19, 0x4a,
	0x23, 0x6d, 0x74, 0xe1, 0xee, 0xce, 0xbd, 0xf7, 0x5c, 0xce, 0xef, 0x04, 0x80, 0x4d, 0x9a, 0x14,
	0x7e, 0xc9, 0x59, 0xc5, 0xa8, 0xae, 0xea, 0x72, 0xe9, 0x3e, 0x07, 0x78, 0x87, 0x42, 0x24, 0x1b,
	0x8c, 0xb1, 0xa2, 0x16, 0xe8, 0xf3, 0xf5, 0x5a, 0x60, 0xe5, 0x90, 0x21, 0xf1, 0x34, 0xfa, 0x00,
	0x8c, 0x76, 0x2a, 0x9c, 0xb3, 0xa1, 0xe6, 0x99, 0xc1, 0x2d, 0x7f, 0x2f, 0xf4, 0xdb, 0xbe, 0xfb,
	0x8b, 0xc0, 0xa0, 0xad, 0xa9, 0x09, 0x5a, 0xb8, 0x08, 0x1b, 0xed, 0x15, 0x1d, 0x81, 0x19, 0xb2,
	0xbc, 0xe4, 0x72, 0x96, 0xb1, 0x42, 0xca, 0x89, 0x67, 0x05, 0xf7, 0x4f, 0xe4, 0x7e, 0xfa, 0x67,
	0x45, 0xc9, 0xdf, 0xe0, 0x0f, 0x47, 0x93, 0x9b, 0x97, 0xf4, 0x0a, 0xce, 0x3f, 0x26, 0xbb, 0x1a,
	0x9d, 0xbe, 0x7a, 0xba, 0x4f, 0xc0, 0xec, 0xae, 0x1a, 0xd0, 0x9f, 0xcd, 0x67, 0x53, 0xbb, 0xa7,
	0xaa, 0xcf, 0x6f, 0x5f, 0x4f, 0x6c, 0x42, 0x01, 0xf4, 0x78, 0xf6, 0x22, 0x8a, 0x3e, 0xd9, 0x67,
	0xee, 0x4b, 0x30, 0x63, 0x2c, 0x56, 0x0b, 0xfc, 0x5a, 0xa3, 0xa8, 0xd4, 0xb1, 0xf7, 0xac, 0xcc,
	0xd2, 0xc6, 0xda, 0x05, 0x7d, 0xd8, 0x85, 0x6e, 0x9c, 0x99, 0x01, 0x3d, 0x71, 0x26, 0x27, 0xae,
	0x05, 0x97, 0xfb, 0x2b, 0xa2, 0x64, 0x85, 0x40, 0x77, 0x02, 0xd6, 0x02, 0x53, 0xcc, 0xbe, 0xe1,
	0x3f, 0x0e, 0x5f, 0xc3, 0x45, 0x94, 0xf0, 0x2a, 0xab, 0x0e, 0xc4, 0xe7, 0x9d, 0x48, 0x15, 0x97,
	0xf6, 0xf8, 0x11, 0x68, 0x53, 0xce, 0x25, 0xeb, 0xe0, 0x43, 0xb1, 0x2d, 0xd8, 0xf7, 0x42, 0x32,
	0xdc, 0x85, 0x6b, 0x99, 0x5b, 0xf8, 0x05, 0xd3, 0xad, 0xa8, 0xf3, 0x57, 0x49, 0xb6, 0xc3, 0x95,
	0x4d, 0x82, 0x9f, 0x60, 0x44, 0x9c, 0xad, 0xea, 0x14, 0x39, 0x1d, 0x43, 0x5f, 0x59, 0xa1, 0xb7,
	0x0f, 0x36, 0x3b, 0x78, 0x37, 0x77, 0x8e, 0x9b, 0xad, 0xdb, 0x1e, 0x7d, 0x06, 0xa0, 0x3a, 0x71,
	0xc5, 0x31, 0xc9, 0xff, 0x4b, 0xea, 0x91, 0x11, 0x09, 0xa6, 0x60, 0x84, 0xf2, 0x59, 0xe7, 0xf2,
	0xfb, 0x4f, 0x61, 0xd0, 0xa2, 0xd3, 0x7b, 0x07, 0xc9, 0x71, 0x16, 0x37, 0x7f, 0x4b, 0xb0, 0x37,
	0x22, 0x4b, 0xbd, 0xf9, 0xe3, 0xc6, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90, 0x25, 0xfd, 0xac,
	0x7f, 0x02, 0x00, 0x00,
}
