// Code generated by protoc-gen-go.
// source: gcan.proto
// DO NOT EDIT!

/*
Package gcanpb is a generated protocol buffer package.

It is generated from these files:
	gcan.proto

It has these top-level messages:
	SendRequest
	SendResponse
	ReceiveRequest
	Response
*/
package gcanpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SendRequest struct {
	Topic string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendResponse struct {
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReceiveRequest struct {
	Topic     string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Partition int32  `protobuf:"varint,2,opt,name=Partition" json:"Partition,omitempty"`
	Offset    int64  `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
}

func (m *ReceiveRequest) Reset()                    { *m = ReceiveRequest{} }
func (m *ReceiveRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiveRequest) ProtoMessage()               {}
func (*ReceiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
	Key   string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*SendRequest)(nil), "gcanpb.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "gcanpb.SendResponse")
	proto.RegisterType((*ReceiveRequest)(nil), "gcanpb.ReceiveRequest")
	proto.RegisterType((*Response)(nil), "gcanpb.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Producer service

type ProducerClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	SendStream(ctx context.Context, opts ...grpc.CallOption) (Producer_SendStreamClient, error)
}

type producerClient struct {
	cc *grpc.ClientConn
}

func NewProducerClient(cc *grpc.ClientConn) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := grpc.Invoke(ctx, "/gcanpb.Producer/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (Producer_SendStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Producer_serviceDesc.Streams[0], c.cc, "/gcanpb.Producer/SendStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerSendStreamClient{stream}
	return x, nil
}

type Producer_SendStreamClient interface {
	Send(*SendRequest) error
	Recv() (*SendResponse, error)
	grpc.ClientStream
}

type producerSendStreamClient struct {
	grpc.ClientStream
}

func (x *producerSendStreamClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerSendStreamClient) Recv() (*SendResponse, error) {
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Producer service

type ProducerServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	SendStream(Producer_SendStreamServer) error
}

func RegisterProducerServer(s *grpc.Server, srv ProducerServer) {
	s.RegisterService(&_Producer_serviceDesc, srv)
}

func _Producer_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ProducerServer).Send(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Producer_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServer).SendStream(&producerSendStreamServer{stream})
}

type Producer_SendStreamServer interface {
	Send(*SendResponse) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type producerSendStreamServer struct {
	grpc.ServerStream
}

func (x *producerSendStreamServer) Send(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerSendStreamServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Producer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcanpb.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Producer_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _Producer_SendStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

// Client API for Consumer service

type ConsumerClient interface {
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (Consumer_ReceiveClient, error)
}

type consumerClient struct {
	cc *grpc.ClientConn
}

func NewConsumerClient(cc *grpc.ClientConn) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (Consumer_ReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Consumer_serviceDesc.Streams[0], c.cc, "/gcanpb.Consumer/Receive", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consumer_ReceiveClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type consumerReceiveClient struct {
	grpc.ClientStream
}

func (x *consumerReceiveClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Consumer service

type ConsumerServer interface {
	Receive(*ReceiveRequest, Consumer_ReceiveServer) error
}

func RegisterConsumerServer(s *grpc.Server, srv ConsumerServer) {
	s.RegisterService(&_Consumer_serviceDesc, srv)
}

func _Consumer_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServer).Receive(m, &consumerReceiveServer{stream})
}

type Consumer_ReceiveServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type consumerReceiveServer struct {
	grpc.ServerStream
}

func (x *consumerReceiveServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _Consumer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gcanpb.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _Consumer_Receive_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0x4e, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0x94, 0x2c, 0xb8, 0xb8,
	0x83, 0x53, 0xf3, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x78, 0xb9, 0x58, 0x43,
	0xf2, 0x0b, 0x32, 0x93, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x85, 0xb8, 0xb9, 0x98, 0xbd, 0x53,
	0x2b, 0x25, 0x98, 0xc0, 0x1c, 0xa0, 0x5c, 0x58, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x33, 0x90, 0xcb,
	0xa3, 0xc4, 0xc7, 0xc5, 0x03, 0xd1, 0x59, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0xe4, 0xc4, 0xc5,
	0x17, 0x94, 0x9a, 0x9c, 0x9a, 0x59, 0x96, 0x8a, 0xc3, 0x30, 0x41, 0x2e, 0xce, 0x80, 0xc4, 0xa2,
	0x92, 0xcc, 0x92, 0xcc, 0xfc, 0x3c, 0xb0, 0x91, 0xac, 0x42, 0x7c, 0x5c, 0x6c, 0xfe, 0x69, 0x69,
	0xc5, 0xa9, 0x25, 0x60, 0x33, 0x99, 0x95, 0xd4, 0xb8, 0x38, 0x60, 0xe6, 0xe1, 0xb3, 0xdb, 0xa8,
	0x8e, 0x8b, 0x23, 0xa0, 0x28, 0x3f, 0xa5, 0x34, 0x39, 0xb5, 0x48, 0xc8, 0x98, 0x8b, 0x05, 0xe4,
	0x0e, 0x21, 0x61, 0x3d, 0x88, 0x97, 0xf4, 0x90, 0xfc, 0x23, 0x25, 0x82, 0x2a, 0x08, 0x75, 0x2a,
	0x83, 0x90, 0x2d, 0x17, 0x17, 0x48, 0x24, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x97, 0x24, 0xad, 0x1a,
	0x8c, 0x06, 0x8c, 0x46, 0xce, 0x5c, 0x1c, 0xce, 0x40, 0x6e, 0x69, 0x2e, 0xd0, 0x7e, 0x73, 0x2e,
	0x76, 0xa8, 0xbf, 0x85, 0xc4, 0x60, 0x5a, 0x50, 0x03, 0x42, 0x4a, 0x00, 0x21, 0x0e, 0x33, 0xc6,
	0x80, 0x31, 0x89, 0x0d, 0x1c, 0x13, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xc6, 0xa8,
	0x93, 0x97, 0x01, 0x00, 0x00,
}
