.TH gcand 1 ""
.SH NAME
gcand \- gcan daemon
.SH SYNOPSIS
\fBgcand\fP [OPTIONS]
.SH DESCRIPTION

.SH OPTIONS
.TP
\fB\fB\-v\fR, \fB\-\-verbose\fR\fP
Be verbose
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
.SH COMMANDS
.SS start
starts the gcand daemon

\fBUsage\fP: gcand [OPTIONS] start [start-OPTIONS]
.TP
.TP
\fB\fB\-l\fR, \fB\-\-listen\fR <default: \fI":4226"\fR>\fP
Listen address
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
